const data = {
  categories: [
    {
      name: "Popular",
      image: "/images/seafoodpizza.png",
    },

    {
      name: "Pizza",
      image: "/images/pizza1.png",
    },
    {
      name: "Burgers",
      image: "/images/burger.png",
    },
    {
      name: "Crepe",
      image: "/images/crepe3.png",
    },

    {
      name: "Drinks",
      image: "/images/beverages.jpeg",
    },
  ],
  products: [

    {
      category: "Popular",
      name: "Pepperoni",
      price: 1.9,
      calorie: 200,
      image: "/images/pizza1.png",
    },
    {
      category: "Popular",
      name: "Anchovy",
      price: 1.5,
      calorie: 410,
      image: "/images/seafoodpizza.png",
    },
    {
      category: "Popular",
      name: "Pepperoni",
      price: 1.9,
      calorie: 200,
      image: "/images/pizza1.png",
    },
    {
      category: "Popular",
      name: "Anchovy",
      price: 1.5,
      calorie: 410,
      image: "/images/seafoodpizza.png",
    },
    {
      category: "Popular",
      name: "Burrata",
      price: 3,
      calorie: 320,
      image: "/images/veg.png",
    },
    {
      category: "Popular",
      name: " Mix Cheese",
      price: 1.9,
      calorie: 200,
      image: "/images/pizza1.png",
    },
    {
      category: "Popular",
      name: "Chicken Ranch",
      price: 1.5,
      calorie: 410,
      image: "/images/seafoodpizza.png",
    },
    {
      category: "Popular",
      name: "Margherita",
      price: 3,
      calorie: 320,
      image: "/images/veg.png",
    },

    {
      category: "Pizza",
      name: "Pepperoni",
      price: 1.9,
      calorie: 200,
      image: "/images/pizza1.png",
    },
    {
      category: "Pizza",
      name: "Anchovy",
      price: 1.5,
      calorie: 410,
      image: "/images/seafoodpizza.png",
    },
    {
      category: "Pizza",
      name: "Pepperoni",
      price: 1.9,
      calorie: 200,
      image: "/images/pizza1.png",
    },
    {
      category: "Pizza",
      name: "Anchovy",
      price: 1.5,
      calorie: 410,
      image: "/images/seafoodpizza.png",
    },
    {
      category: "Pizza",
      name: "Veggie",
      price: 3,
      calorie: 320,
      image: "/images/veg.png",
    },
    {
      category: "Pizza",
      name: "Prosciutto e funghi",
      price: 1.9,
      calorie: 200,
      image: "/images/pizza1.png",
    },
    {
      category: "Pizza",
      name: "Marinara",
      price: 1.5,
      calorie: 410,
      image: "/images/seafoodpizza.png",
    },
    {
      category: "Pizza",
      name: "Diavola",
      price: 3,
      calorie: 320,
      image: "/images/veg.png",
    },
    {
      category: "Burgers",
      name: "Double Cheese",
      price: 1.9,
      calorie: 200,
      image: "/images/t-mcdonalds-Big-Mac.jpg",
    },
    {
      category: "Burgers",
      name: "Single Hamburger",
      price: 1.5,
      calorie: 410,
      image: "/images/t-mcdonalds-Hamburger.jpg",
    },
    {
      category: "Burgers",
      name: "Double Cheese",
      price: 1.9,
      calorie: 200,
      image: "/images/t-mcdonalds-Big-Mac.jpg",
    },
    {
      category: "Burgers",
      name: "Single Hamburger",
      price: 1.5,
      calorie: 410,
      image: "/images/t-mcdonalds-Hamburger.jpg",
    },
    {
      category: "Burgers",
      name: "Big Mouth",
      price: 3,
      calorie: 320,
      image: "/images/t-mcdonalds-McDouble.jpg",
    },

    {
      category: "Burgers",
      name: "Cheese Chicken",
      price: 1.9,
      calorie: 200,
      image: "/images/t-mcdonalds-Big-Mac.jpg",
    },
    {
      category: "Burgers",
      name: "Small Hamburger",
      price: 1.5,
      calorie: 410,
      image: "/images/t-mcdonalds-Hamburger.jpg",
    },
    {
      category: "Burgers",
      name: "Whopper",
      price: 3,
      calorie: 320,
      image: "/images/t-mcdonalds-McDouble.jpg",
    },
    {
      category: "Crepe",
      name: "Strawberry  & Chocolate",
      price: 1.9,
      calorie: 90,
      image:
        "/images/crepe3.png",
    },
    {
      category: "Crepe",
      name: "Strawberry  & Chocolate",
      price: 1.9,
      calorie: 90,
      image: "/images/crepe3.png",
    },
    {
      category: "Crepe",
      name: "Strawberry  & Chocolate",
      price: 1.9,
      calorie: 90,
      image:
        "/images/crepe3.png",
    },
    {
      category: "Crepe",
      name: "Blueberry Banana",
      price: 1.5,
      calorie: 120,
      image: "/images/crepe1.png",
    },
    {
      category: "Crepe",
      name: "Cinnamon ",
      price: 3,
      calorie: 430,
      image: "/images/crepe2.png",
    },
    {
      category: "Crepe",
      name: "Strawberry  & Chocolate",
      price: 1.9,
      calorie: 90,
      image:"/images/crepe1.png",
    },
    {
      category: "Crepe",
      name: "Blueberry Banana",
      price: 1.5,
      calorie: 120,
      image: "/images/crepe1.png",
    },
    {
      category: "Crepe",
      name: "Cinnamon ",
      price: 3,
      calorie: 430,
      image: "/images/crepe3.png",
    },

    {
      category: "Drinks",
      Name: "Coca Cola",
      calorie: "100",
      price: "1",
      image: "/images/cocacola.png",
    },
    {
      category: "Drinks",
      name: "sprite",
      price: 1.5,
      calorie: 360,
      image: "/images/sprite.png",
    },
    {
      category: "Drinks",
      name: "Fanta",
      price: 2,
      calorie: 170,
      image: "/images/fanta.png",
    },
    {
      category: "Drinks",
      Name: "Coca Cola",
      calorie: "100",
      price: "1",
      image: "/images/cocacola.png",
    },
    {
      category: "Drinks",
      name: "sprite",
      price: 1.5,
      calorie: 360,
      image: "/images/sprite.png",
    },
    {
      category: "Drinks",
      name: "Fanta",
      price: 2,
      calorie: 170,
      image: "/images/fanta.png",
    },
  ],
};

module.exports = data;
